-- Seed only the 14 courses shown in the supplied institute brochures.
-- Run after supabase.sql, which creates the courses table and its enum types.
INSERT INTO public.courses (
  slug, name, short_name, duration, type, description, full_description,
  topics, fees, fee_numeric, eligibility, certification, certifications,
  certification_body, highlights, schedule, batch_size
) VALUES
  ('adca', 'Advanced Diploma in Computer Application (A.D.C.A.)', 'A.D.C.A.', '65 Days', 'long-term',
   'Advanced diploma in computer applications.', 'Computer applications, office tools, internet skills and accounting topics.',
   ARRAY['Computer Basics','Typing Master','Windows Concepts','MS-Word','MS-Excel','MS-PowerPoint','Internet Skills','Live Projects','Manual A/c Basic','Tally Prime Software','Groups / Ledgers / Vouchers','Account Billings','Cost Accounts / BRS','Inventory Billings / Payroll','GST / SGST / CGST / IGST','Cess and TDS Billings'],
   '₹6,500', 6500, 'Not specified in brochure', 'Course Completion Certificate', ARRAY['Advanced Diploma in Computer Application (A.D.C.A.)'],
   'The New Generation Computers', ARRAY['Includes 2 books, 2 exams and 2 certificates'], 'Not specified in brochure', 'Not specified in brochure'),
  ('dca', 'Diploma in Computer Application (D.C.A.)', 'D.C.A.', '40 Days', 'long-term',
   'Diploma in computer applications.', 'Computer basics, typing, Windows, office tools, internet skills and live projects.',
   ARRAY['Computer Basics','Typing Master','Windows Concepts','MS-Word','MS-Excel','MS-PowerPoint','Internet Skills','Live Projects'],
   '₹3,500', 3500, 'Not specified in brochure', 'Course Completion Certificate', ARRAY['Diploma in Computer Application (D.C.A.)'],
   'The New Generation Computers', ARRAY['Includes 1 book, 1 exam and 1 certificate'], 'Not specified in brochure', 'Not specified in brochure'),
  ('dct', 'Diploma in Computer Accounting + Tally Prime (D.C.T.)', 'D.C.T.', '35 Days', 'long-term',
   'Diploma in computer accounting and Tally Prime.', 'Manual accounting, Tally Prime, ledgers, vouchers, billing, inventory, payroll, GST and TDS.',
   ARRAY['Manual A/c Basic','Tally Prime Software','Groups / Ledgers','Vouchers Entry','Account Billings','Cost Accounts / BRS','Inventory Billings / Payroll','GST / SGST / CGST / IGST','Cess and TDS Billings'],
   '₹3,500', 3500, 'Not specified in brochure', 'Course Completion Certificate', ARRAY['Diploma in Computer Accounting + Tally Prime (D.C.T.)'],
   'The New Generation Computers', ARRAY['Includes 1 book, 1 exam and 1 certificate'], 'Not specified in brochure', 'Not specified in brochure'),
  ('dcl', 'Diploma in C Programming Language (D.C.L.)', 'D.C.L.', '45 Days', 'long-term',
   'Diploma in C programming language.', 'C fundamentals, control flow, arrays, functions, pointers, memory, structures, unions and file handling.',
   ARRAY['C Basics','C Tokens','Decision Making Statements','Looping Statements','Arrays & Strings','Functions & Recursion','Storage Classes','Pointers','Dynamic Memory','Structures & Unions','Preprocessor Directives','File Handling in C'],
   '₹4,500', 4500, 'Not specified in brochure', 'Course Completion Certificate', ARRAY['Diploma in C Programming Language (D.C.L.)'],
   'The New Generation Computers', ARRAY['Includes 1 book, 1 exam and 1 certificate'], 'Not specified in brochure', 'Not specified in brochure'),
  ('pgdca', 'Post Graduate Diploma in Computer Application (P.G.D.C.A.)', 'P.G.D.C.A.', '75 Days', 'long-term',
   'Post graduate diploma in computer applications.', 'Computer basics, office tools, internet skills and C language.',
   ARRAY['Computer Basics','MS-Word','MS-Excel','MS-PowerPoint','Internet Skills','C Language'],
   '₹7,000', 7000, 'Not specified in brochure', 'Course Completion Certificate', ARRAY['Post Graduate Diploma in Computer Application (P.G.D.C.A.)'],
   'The New Generation Computers', ARRAY['Includes 2 books, 2 exams and 1 certificate'], 'Not specified in brochure', 'Not specified in brochure'),
  ('pgjpl', 'Post Graduate Diploma in Core Java Programming Language (P.G.C.J.P.L.)', 'P.G.C.J.P.L.', '50 Days', 'long-term',
   'Post graduate diploma in core Java programming.', 'Java fundamentals, object-oriented programming, exceptions, arrays, collections and Java utility packages.',
   ARRAY['Introduction to Java','Control Statements','Looping Statements','Classes & Objects','Inheritance','Polymorphism','Abstractions','Encapsulation','I/O Streams','Interfaces & Packages','Exception Handling','Multithreading','String Handling','Arrays','Collections','Java Util Package'],
   '₹5,000', 5000, 'Not specified in brochure', 'Course Completion Certificate', ARRAY['Post Graduate Diploma in Core Java Programming Language (P.G.C.J.P.L.)'],
   'The New Generation Computers', ARRAY['Includes 1 book, 1 exam and 1 certificate'], 'Not specified in brochure', 'Not specified in brochure'),
  ('pgajpl', 'Post Graduate Diploma in Advanced Java Programming Language (P.G.A.J.L.)', 'P.G.A.J.L.', '50 Days', 'long-term',
   'Post graduate diploma in advanced Java programming.', 'Java 8, functional programming, JDBC, MySQL, joins and procedures.',
   ARRAY['Introduction to Java 8','Lambda Expressions','Functional Interfaces','Streams API','Default Methods','Static Methods','Optional Classes','Date & Time API','JDBC','Statement Interfaces','Prepared Statement','ResultSet Interfaces','Introduction to DB','MySQL','MySQL Commands','Joins & Procedures'],
   '₹5,000', 5000, 'Not specified in brochure', 'Course Completion Certificate', ARRAY['Post Graduate Diploma in Advanced Java Programming Language (P.G.A.J.L.)'],
   'The New Generation Computers', ARRAY['Includes 1 book, 1 exam and 1 certificate'], 'Not specified in brochure', 'Not specified in brochure'),
  ('pgcpl', 'Post Graduate Diploma in Core Python Programming Language (P.G.C.P.L.)', 'P.G.C.P.L.', '45 Days', 'long-term',
   'Post graduate diploma in core Python programming.', 'Python fundamentals, data types, operators, control flow, data structures, strings, modules, packages and file handling.',
   ARRAY['Introduction to Python','Variables & Data Types','Operators','Control Statements','Data Structures','Strings & Functions','Modules','Packages','File Handling','Exception Handling'],
   '₹4,500', 4500, 'Not specified in brochure', 'Course Completion Certificate', ARRAY['Post Graduate Diploma in Core Python Programming Language (P.G.C.P.L.)'],
   'The New Generation Computers', ARRAY['Includes 1 book, 1 exam and 1 certificate'], 'Not specified in brochure', 'Not specified in brochure'),
  ('pgappl', 'Post Graduate Diploma in Advanced Python Programming Language (P.G.A.P.L.)', 'P.G.A.P.L.', '50 Days', 'long-term',
   'Post graduate diploma in advanced Python programming.', 'Object-oriented concepts, exceptions, databases, SQL, Python with MySQL and projects.',
   ARRAY['OOPs Concepts','Methods & Variables','Inheritance','Polymorphism','Abstraction','Encapsulation','Multithreading','Exceptions','Introduction to DB','MySQL','Basic SQL Commands','Joins & Sub Queries','Python with MySQL','Python Projects'],
   '₹5,000', 5000, 'Not specified in brochure', 'Course Completion Certificate', ARRAY['Post Graduate Diploma in Advanced Python Programming Language (P.G.A.P.L.)'],
   'The New Generation Computers', ARRAY['Includes 1 book, 1 exam and 1 certificate'], 'Not specified in brochure', 'Not specified in brochure'),
  ('dsl', 'Diploma in Data Structure Language (D.S.L.)', 'D.S.L.', '60 Days', 'long-term',
   'Diploma in data structure language.', 'Data structures, searching, sorting and common algorithmic techniques.',
   ARRAY['Introduction to Data Structures','Arrays & Strings','Linked Lists','Searching','Stacks & Queues','Trees','Graphs','Sorting'],
   '₹6,000', 6000, 'Not specified in brochure', 'Course Completion Certificate', ARRAY['Diploma in Data Structure Language (D.S.L.)'],
   'The New Generation Computers', ARRAY['Includes 1 book, 1 exam and 1 certificate'], 'Not specified in brochure', 'Not specified in brochure'),
  ('pdds', 'Post Graduation Diploma in Data Science (P.D.D.S.)', 'P.D.D.S.', '90 Days', 'long-term',
   'Post graduation diploma in data science.', 'Python, data structures, NumPy, Pandas, visualization, statistics, correlation, regression and data preprocessing.',
   ARRAY['Python Basics','Data Structures','NumPy','Pandas','Matplotlib & Seaborn','Data Visualization','Descriptive Statistics','Correlation','Regression','Data Preprocessing'],
   '₹9,000', 9000, 'Not specified in brochure', 'Course Completion Certificate', ARRAY['Post Graduation Diploma in Data Science (P.D.D.S.)'],
   'The New Generation Computers', ARRAY['Includes 1 book, 1 exam and 1 certificate'], 'Not specified in brochure', 'Not specified in brochure'),
  ('java-full-stack', 'Java Full Stack Development', 'Java Full Stack', '180 Days', 'long-term',
   'Full stack Java development programme.', 'Core Java, JDK 8+, MySQL, JDBC, HTML, CSS, JavaScript, ReactJS, Spring Boot and microservices.',
   ARRAY['Core Java','JDK 8+ Concepts','MySQL','JDBC','HTML, CSS, JS','React JS','Spring Boot','Micro Services'],
   '₹30,000', 30000, 'Not specified in brochure', 'Course Completion Certificate', ARRAY['Java Full Stack Development'],
   'The New Generation Computers', ARRAY['Includes 4 books, 4 exams and 1 certificate'], 'Not specified in brochure', 'Not specified in brochure'),
  ('python-full-stack', 'Python Full Stack Development', 'Python Full Stack', '180 Days', 'long-term',
   'Full stack Python development programme.', 'Core Python, Advanced Python, MySQL, HTML, CSS, JavaScript, ReactJS, Flask, testing and deployment.',
   ARRAY['Core Python','Advanced Python','MySQL','HTML, CSS, JS','React JS','Flask Framework','Testing','Deployment'],
   '₹30,000', 30000, 'Not specified in brochure', 'Course Completion Certificate', ARRAY['Python Full Stack Development'],
   'The New Generation Computers', ARRAY['Includes 4 books, 4 exams and 1 certificate'], 'Not specified in brochure', 'Not specified in brochure'),
  ('front-end-development', 'Front-End Development', 'Front-End Development', '90 Days', 'long-term',
   'Front-end development programme.', 'HTML5, CSS, JavaScript, Bootstrap, ReactJS and projects.',
   ARRAY['HTML 5','CSS','JavaScript','Bootstrap','React JS','Projects'],
   '₹8,500', 8500, 'Not specified in brochure', 'Course Completion Certificate', ARRAY['Front-End Development'],
   'The New Generation Computers', ARRAY['Includes 2 books, 2 exams and 1 certificate'], 'Not specified in brochure', 'Not specified in brochure')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  short_name = EXCLUDED.short_name,
  duration = EXCLUDED.duration,
  type = EXCLUDED.type,
  description = EXCLUDED.description,
  full_description = EXCLUDED.full_description,
  topics = EXCLUDED.topics,
  fees = EXCLUDED.fees,
  fee_numeric = EXCLUDED.fee_numeric,
  eligibility = EXCLUDED.eligibility,
  certification = EXCLUDED.certification,
  certifications = EXCLUDED.certifications,
  certification_body = EXCLUDED.certification_body,
  highlights = EXCLUDED.highlights,
  schedule = EXCLUDED.schedule,
  batch_size = EXCLUDED.batch_size,
  updated_at = NOW();
